spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_for_online_store_db
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: public
  packages-to-scan:
    - com.example.backend.entity
